name: Deploy Node.js to Azure Web App

on:
  push

env:
  AZURE_WEBAPP_NAME: 519fall2023-assignment1
  AZURE_WEBAPP_PACKAGE_PATH: './Node/WEB/frontend' # Path to your web app project
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and build frontend
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          npm install
          npm run build
          # Optionally run tests
          # npm run test --if-present

      - name: Prepare for deployment
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          # Remove non-essential directories
          rm -rf node_modules src public
          # Now, only the 'build' directory and any other necessary files remain

      - name: Zip build artifacts for deployment
        working-directory: ${{ github.workspace }} # Stays at the project root
        run: |
          zip -r release.zip ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d deploy

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy
