name: Deploy Node.js to Azure Web App

on:
  push:
    branches: ["main"]
    paths: "/Node/WEB/**"
    
env:
  AZURE_WEBAPP_NAME: 519fall2023-assignment1
  AZURE_FRONTEND_PACKAGE_PATH: 'Node/WEB/frontend'
  AZURE_WEBAPP_PACKAGE_PATH: 'Node/WEB/' # Path to your web app project
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './Node/WEB/package.json'

      - name: npm install, build, and test
        working-directory: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        run:
          npm install

      - name: Install and build frontend
        working-directory: './${{ env.AZURE_FRONTEND_PACKAGE_PATH }}'
        run: |
          npm install
          npm run build
          # npm run test --if-present
          rm -r node_modules src public

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
